recipient_name = input("What is the recipient's name?")
birth_year = int(input("Enter recipient's birth year:"))
age = 2025 - birth_year
text = input("Personalized message")
sender_name = input("What is the sender's name?")
print()
print(f"{recipient_name}, let's celebrate your {age} years of awesomeness!")
print(f"Wishing you a day filled with joy and laughter as you turn {age}!")
print(f"{text}")
print("With love and best wishes,")
print(f"{sender_name}")
